namespace: community
name: ollama
version: 1.0.0
readme: README.md
authors:
  - "Community Ollama Collection Team"
description: Ansible collection for managing Ollama with Docker
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - docker
  - ollama
  - ai
  - machine_learning
  - llm
dependencies: {}
repository: https://github.com/community/ollama-ansible-collection
documentation: https://github.com/community/ollama-ansible-collection
homepage: https://github.com/community/ollama-ansible-collection
issues: https://github.com/community/ollama-ansible-collection/issues
build_ignore:
  - .gitignore
  - .github
  - .idea
  - tests/output
  - molecule/*/molecule.yml.j2