---
# Обработчики для роли Ollama

- name: restart ollama
  community.docker.docker_container:
    name: "{{ ollama_container_name }}"
    state: started
    restart: true
  listen: restart ollama

- name: stop ollama
  community.docker.docker_container:
    name: "{{ ollama_container_name }}"
    state: stopped
  listen: stop ollama

- name: start ollama
  community.docker.docker_container:
    name: "{{ ollama_container_name }}"
    state: started
  listen: start ollama

- name: reload docker
  ansible.builtin.systemd:
    name: docker
    state: reloaded
  become: true
  listen: reload docker

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true
  listen: restart docker